//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.4
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from FilterParser.g4 by ANTLR 4.6.4

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace OnlineWallet.Web.QueryLanguage.Parser {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="FilterParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.4")]
[System.CLSCompliant(false)]
public interface IFilterParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="FilterParser.filter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFilter([NotNull] FilterParser.FilterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FilterParser.filter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFilter([NotNull] FilterParser.FilterContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FilterParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimary([NotNull] FilterParser.PrimaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FilterParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimary([NotNull] FilterParser.PrimaryContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FilterParser.andTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAndTerm([NotNull] FilterParser.AndTermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FilterParser.andTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAndTerm([NotNull] FilterParser.AndTermContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FilterParser.orTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrTerm([NotNull] FilterParser.OrTermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FilterParser.orTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrTerm([NotNull] FilterParser.OrTermContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="FilterParser.searchTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSearchTerm([NotNull] FilterParser.SearchTermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FilterParser.searchTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSearchTerm([NotNull] FilterParser.SearchTermContext context);
}
} // namespace OnlineWallet.Web.QueryLanguage.Parser
