/**
 * Wallet API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { MoneyDirection } from "./MoneyDirection";

export interface ExportImportRow {
    created?: Date;

    name?: string;

    comment?: string;

    category?: string;

    amount?: number;

    source?: string;

    direction?: MoneyDirection;

    matchingId?: number;

}
