/**
 * Wallet API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ExportImportRow {
    created?: Date;

    name?: string;

    comment?: string;

    category?: string;

    amount?: number;

    source?: ExportImportRow.SourceEnum;

    direction?: ExportImportRow.DirectionEnum;

}
export namespace ExportImportRow {
    export enum SourceEnum {
        NUMBER_0 = <any> 0,
        NUMBER_1 = <any> 1
    }
    export enum DirectionEnum {
        NUMBER_1 = <any> 1,
        NUMBER_MINUS_1 = <any> -1
    }
}
