/**
 * Wallet API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface MoneyOperation {
    moneyOperationId?: number;

    createdAt: Date;

    name: string;

    value: number;

    direction: MoneyOperation.DirectionEnum;

    comment?: string;

    walletId: number;

}
export namespace MoneyOperation {
    export enum DirectionEnum {
        NUMBER_1 = <any> 1,
        NUMBER_MINUS_1 = <any> -1
    }
}
