/**
 * Wallet API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Transaction {
    comment?: string;

    createdAt: Date;

    direction: Transaction.DirectionEnum;

    transactionId?: number;

    name: string;

    value: number;

    walletId: number;

}
export namespace Transaction {
    export enum DirectionEnum {
        NUMBER_1 = <any> 1,
        NUMBER_MINUS_1 = <any> -1
    }
}
