/**
 * Wallet API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { Http, Headers, URLSearchParams }                    from '@angular/http';
import { RequestMethod, RequestOptions, RequestOptionsArgs } from '@angular/http';
import { Response, ResponseContentType }                     from '@angular/http';

import { Observable }                                        from 'rxjs/Observable';
import 'rxjs/add/operator/map';

import * as models                                           from '../model/models';
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class MoneyOperationApi {

    protected basePath = 'https://localhost';
    public defaultHeaders: Headers = new Headers();
    public configuration: Configuration = new Configuration();

    constructor(protected http: Http, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
        }
    }

    /**
     * 
     * @summary Deletes a MoneyOperation by unique id
     * @param id a unique id for the MoneyOperation
     */
    public apiV1MoneyOperationByIdDelete(id: number, extraHttpRequestParams?: any): Observable<models.MoneyOperation> {
        return this.apiV1MoneyOperationByIdDeleteWithHttpInfo(id, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     * 
     * @summary Retrieves a MoneyOperation by unique id
     * @param id 
     */
    public apiV1MoneyOperationByIdGet(id: number, extraHttpRequestParams?: any): Observable<models.MoneyOperation> {
        return this.apiV1MoneyOperationByIdGetWithHttpInfo(id, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     * 
     * @summary Updates a MoneyOperation by unique id
     * @param id a unique id for the MoneyOperation
     * @param value a MoneyOperation representation
     */
    public apiV1MoneyOperationByIdPut(id: number, value?: models.MoneyOperation, extraHttpRequestParams?: any): Observable<models.MoneyOperation> {
        return this.apiV1MoneyOperationByIdPutWithHttpInfo(id, value, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     * 
     * @summary Returns all MoneyOperations
     * @param search 
     * @param skip 
     * @param take 
     */
    public apiV1MoneyOperationGet(search?: string, skip?: number, take?: number, extraHttpRequestParams?: any): Observable<Array<models.MoneyOperation>> {
        return this.apiV1MoneyOperationGetWithHttpInfo(search, skip, take, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     * 
     * @summary Creates a MoneyOperation
     * @param comment a MoneyOperation representation
     * @param createdAt 
     * @param direction 
     * @param moneyOperationId 
     * @param name 
     * @param value 
     * @param walletMoneyWalletId 
     * @param walletName 
     * @param walletId 
     */
    public apiV1MoneyOperationPost(comment?: string, createdAt?: Date, direction?: number, moneyOperationId?: number, name?: string, value?: number, walletMoneyWalletId?: number, walletName?: string, walletId?: number, extraHttpRequestParams?: any): Observable<models.MoneyOperation> {
        return this.apiV1MoneyOperationPostWithHttpInfo(comment, createdAt, direction, moneyOperationId, name, value, walletMoneyWalletId, walletName, walletId, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }


    /**
     * Deletes a MoneyOperation by unique id
     * 
     * @param id a unique id for the MoneyOperation
     */
    public apiV1MoneyOperationByIdDeleteWithHttpInfo(id: number, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/api/v1/MoneyOperation/${id}'
                    .replace('${' + 'id' + '}', String(id));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiV1MoneyOperationByIdDelete.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        // to determine the Accept header
        let produces: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Delete,
            headers: headers,
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Retrieves a MoneyOperation by unique id
     * 
     * @param id 
     */
    public apiV1MoneyOperationByIdGetWithHttpInfo(id: number, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/api/v1/MoneyOperation/${id}'
                    .replace('${' + 'id' + '}', String(id));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiV1MoneyOperationByIdGet.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        // to determine the Accept header
        let produces: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Updates a MoneyOperation by unique id
     * 
     * @param id a unique id for the MoneyOperation
     * @param value a MoneyOperation representation
     */
    public apiV1MoneyOperationByIdPutWithHttpInfo(id: number, value?: models.MoneyOperation, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/api/v1/MoneyOperation/${id}'
                    .replace('${' + 'id' + '}', String(id));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiV1MoneyOperationByIdPut.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];

        headers.set('Content-Type', 'application/json');

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Put,
            headers: headers,
            body: value == null ? '' : JSON.stringify(value), // https://github.com/angular/angular/issues/10612
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Returns all MoneyOperations
     * 
     * @param search 
     * @param skip 
     * @param take 
     */
    public apiV1MoneyOperationGetWithHttpInfo(search?: string, skip?: number, take?: number, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/api/v1/MoneyOperation';

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        if (search !== undefined) {
            queryParameters.set('Search', <any>search);
        }

        if (skip !== undefined) {
            queryParameters.set('Skip', <any>skip);
        }

        if (take !== undefined) {
            queryParameters.set('Take', <any>take);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        // to determine the Accept header
        let produces: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Creates a MoneyOperation
     * 
     * @param comment a MoneyOperation representation
     * @param createdAt 
     * @param direction 
     * @param moneyOperationId 
     * @param name 
     * @param value 
     * @param walletMoneyWalletId 
     * @param walletName 
     * @param walletId 
     */
    public apiV1MoneyOperationPostWithHttpInfo(comment?: string, createdAt?: Date, direction?: number, moneyOperationId?: number, name?: string, value?: number, walletMoneyWalletId?: number, walletName?: string, walletId?: number, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/api/v1/MoneyOperation';

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        if (comment !== undefined) {
            queryParameters.set('Comment', <any>comment);
        }

        if (createdAt !== undefined) {
            queryParameters.set('CreatedAt', <any>createdAt.toISOString());
        }

        if (direction !== undefined) {
            queryParameters.set('Direction', <any>direction);
        }

        if (moneyOperationId !== undefined) {
            queryParameters.set('MoneyOperationId', <any>moneyOperationId);
        }

        if (name !== undefined) {
            queryParameters.set('Name', <any>name);
        }

        if (value !== undefined) {
            queryParameters.set('Value', <any>value);
        }

        if (walletMoneyWalletId !== undefined) {
            queryParameters.set('Wallet.MoneyWalletId', <any>walletMoneyWalletId);
        }

        if (walletName !== undefined) {
            queryParameters.set('Wallet.Name', <any>walletName);
        }

        if (walletId !== undefined) {
            queryParameters.set('WalletId', <any>walletId);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        // to determine the Accept header
        let produces: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

}
